config/routes.rb
Micropost::Application.routes.draw do
 

 
  resources :troubles
  resources :troubles do
  resources :coments
end

  resources :works

  resources :clients

  resources :tickets

  get "welcome/index"

  resources :abouts

  resources :faqs

  resources :contacts

  resources :movies
 

  

  resources :employees

  resources :articles

  resources :articles do
  resources :comments
end

  devise_for :users

  resources :posts

  resources :users

  root :to => 'welcome#index'
  match 'troubles/:state/cerrado', to: 'troubles#cerrado', as: "cerrado"
  match 'troubles/:state/abierto',to: 'troubles#abierto',as:"abierto"
  

end

app/models/trouble.rb
class Trouble < ActiveRecord::Base
	has_many :coments, dependent: :destroy

	belongs_to :client
	belongs_to :user
  attr_accessible :category, :client_id, :severity, :state, :text, :title, :user_id, :image

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/assets/movies.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/


end

app/controllers/troubles_controller.rb
class TroublesController < ApplicationController
before_filter :authenticate_user!
http_basic_authenticate_with name: "cano19781", password: "caracas1", except: [:index, :show]

   
  # GET /troubles
  # GET /troubles.json
def abierto
  @troubles = Trouble.order.paginate(:per_page => 8, :page => params[:page]).where(:state=>"Abierto")
  @numero = Trouble.where(:state=>"Abierto").count
end

def cerrado
  @troubles = Trouble.order.paginate(:per_page => 8, :page => params[:page]).where(:state=>"Cerrado")
  @numero = Trouble.where(:state=>"Cerrado").count
end

  def index
    @troubles = Trouble.all
    @troubles = Trouble.order.paginate(:per_page => 5, :page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @troubles }
    end
  end

  # GET /troubles/1
  # GET /troubles/1.json
  def show
    @trouble = Trouble.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @trouble }
    end
  end

  # GET /troubles/new
  # GET /troubles/new.json
  def new
    @trouble = Trouble.new
    @users = User.all.map {|user| [user.name, user.id]}

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @trouble }
    end
  end

  # GET /troubles/1/edit
  def edit
    @trouble = Trouble.find(params[:id])
    @users = User.all.map {|user| [user.name, user.id]}
  end

  # POST /troubles
  # POST /troubles.json
  def create
    @trouble = Trouble.new(trouble_params)

    respond_to do |format|
      if @trouble.save
        format.html { redirect_to @trouble, notice: 'El ticket ha sido creado correctamente.' }
        format.json { render json: @trouble, status: :created, location: @trouble }
      else
        format.html { render action: "new" }
        format.json { render json: @trouble.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /troubles/1
  # PATCH/PUT /troubles/1.json
  def update
    @trouble = Trouble.find(params[:id])

    respond_to do |format|
      if @trouble.update_attributes(trouble_params)
        format.html { redirect_to @trouble, notice: 'El ticket ha sido actualizado correctamente.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @trouble.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /troubles/1
  # DELETE /troubles/1.json
  def destroy
    @trouble = Trouble.find(params[:id])
    @trouble.destroy

    respond_to do |format|
      format.html { redirect_to troubles_url }
      format.json { head :no_content }
    end
  end

  private

    # Use this method to whitelist the permissible parameters. Example:
    # params.require(:person).permit(:name, :age)
    # Also, you can specialize this method with per-user checking of permissible attributes.
    def trouble_params
      params.require(:trouble).permit(:category, :client_id, :severity, :state, :text, :title, :user_id, :image)
    end
end

app/helpers/troubles_helper.rb
module TroublesHelper
end

app/views/troubles/_form.html.erb
<%= form_for(@trouble) do |f| %>
  <% if @trouble.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trouble.errors.count, "error") %> prohibited this trouble from being saved:</h2>

      <ul>
      <% @trouble.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  
  
<!-- Imagen o captura del ticket -->  
<div class="row">
    <div class="large-12 columns">
    <label><span data-tooltip aria-haspopup="true" class="has-tip" title="Colocar imagen o captura">Imagen o Captura</span>
    <%= f.file_field :image %>
      </label>
    </div>


  <form>
  <fieldset>
    <legend><h2>Crear Ticket</h2></legend>

<!-- Estatus del ticket -->
      <label><span data-tooltip aria-haspopup="true" class="has-tip" title="Favor indicar estatus del caso">Ticket</span>
  <%= f.radio_button :state, 'Abierto', :checked => true %>
  <%= label :state, 'Abierto' %>
  <%= f.radio_button :state, 'Cerrado' %>
  <%= label :state, 'Cerrado' %>
    </label>


    <hr>

<!-- Cliente del ticket -->
    <div class="large-12 columns">
    <label><span data-tooltip aria-haspopup="true" class="has-tip" title="Colocar cliente">Cliente</span>
    <%= select("trouble", "client_id", Client.find(:all).collect{|c| [c.name, c.id] }) %>
      </label>
    </div>

 
 <!-- Titulo del ticket -->
    <div class="large-12 columns">
    <label><span data-tooltip aria-haspopup="true" class="has-tip" title="Colocar titulo del problema o el requerimiento">Titulo del Problema</span>
    <%= f.text_field :title %>
      </label>
    </div>

  <!-- Problema del ticket -->
    <div class="large-12 columns">
    <label><span data-tooltip aria-haspopup="true" class="has-tip" title="Favor describir el problema o el requerimiento">Descripcion del Problema</span>
    <%= f.text_area :text %>
      </label>
    </div>
  
 <!-- Importancia del ticket -->
    <div class="large-4 columns">
    <label><span data-tooltip aria-haspopup="true" class="has-tip" title="Favor indicar importancia del caso">Importancia</span>
  <% severidad = {'-Seleccione-' => '-Seleccione-', 'Deseable' => 'Deseable', 'Necesario' => 'Necesario', 'Indispensable' => 'Indispensable',} %>
    <%= f.select :severity,severidad %>
     </label>
    </div>
  
 <!-- Categoria del ticket -->
    <div class="large-4 columns">
    <label><span data-tooltip aria-haspopup="true" class="has-tip" title="Favor indicar categoria">Categoria</span>
  <% categoria = {'-Seleccione-' => '-Seleccione-', 'Requerimiento' => 'Requerimiento', 'Soporte' => 'Soporte',} %>
    <%= f.select :category,categoria %>
    </label>
  </div>

  <!-- Usuario que crea el ticket --> 
    <div class="large-12 columns">
    <%= f.label :usuario %><br /> 
    <%= f.select :user_id, options_for_select(@users) %> 
  </div>


<!-- Botones de guardar y atras del ticket -->
  <div class="actions">
  <%= f.submit 'Guardar', class: 'button tiny' %>
    <%= link_to 'Atras', tickets_path, class: 'button tiny' %>
    </div>


   </fieldset>
</form>
<% end %>

 </fieldset>
</form>




<!-- Pie de pagina con los links de retorno --> 
<div class="icon-bar five-up" role="navigation">
  
    
    <label id='itemlabel1'><%= link_to 'Home', root_path %></label>
  </a>

    
    <label id='itemlabel2'><%= link_to 'Preguntas', faqs_path %></label>
  </a>
  
    
    <label id='itemlabel3'><%= link_to 'Nosotros', abouts_path %></label>
  </a>
  
    
    <label id='itemlabel4'><%= link_to 'Contactanos', contacts_path %></label>
  </a>
  
</div>



<!-- Pie de pagina con nombre de creador --> 

<dl class="sub-nav">
  <dt>Creado por:</dt>
  <dd class="active"><a href="#">Rogger Herrera</a></dd>
  <dd><a href="#">Banco San Juan S.A</a></dd>
  <dd><a href="#">2019</a></dd>
</dl>

app/views/troubles/abierto.html.erb
<h3><%=@numero %>, Tickets Abiertos </h3>

<table class="table table-hover">
	<% if !@troubles.blank? %>

<thead>
	<th># ticket</th>
	<th> Cliente </th>
	<th> Titulo</th>
	<th> Fecha</th>
	<th> Categoria</th>
	<th>acciones</th>
</thead>
  <% for item in @troubles %>
    <tbody>
    	<tr>
    	<td><%= link_to item.id, item %></td>
    	<td><%= item.client.name%></td>
    	<td><%= item.title %></td>
    	<td><%= item.created_at.strftime("%d/%m/%y- %H:%M") %></td>
    	<td><%= item.severity %></td>
    	<td>
    		
    	<%= link_to 'Editar', edit_trouble_path(item) %> | 
    	<%= link_to 'Eliminar', item, method: :delete, data: { confirm: 'Desea eliminar este ticket?' } %>


    	</td>
    	</tr>

    </tbody>
  <% end %>
<% else %>
  
<% end %>



</table>



<!-- Atras -->
<%= link_to(image_tag("atras-32.png"), tickets_path) %>
<%= link_to 'Atras', tickets_path %>

<%= will_paginate @troubles %>

app/views/troubles/cerrado.html.erb
<h3><%=@numero %>, Tickets Cerrados </h3>

<table class="table table-hover">
	<% if !@troubles.blank? %>

<thead>
	<th># ticket</th>
	<th> Cliente </th>
	<th> Titulo</th>
	<th> Fecha</th>
	<th> Categoria</th>
	<th>acciones</th>
</thead>
  <% for item in @troubles %>
    <tbody>
    	<tr>
    	<td><%= link_to item.id, item %></td>
    	<td><%= item.client.name%></td>
    	<td><%= item.title %></td>
    	<td><%= item.created_at.strftime("%d/%m/%y- %H:%M") %></td>
    	<td><%= item.severity %></td>
    	<td>
    		
    	<%= link_to 'Editar', edit_trouble_path(item) %> | 
    	<%= link_to 'Eliminar', item, method: :delete, data: { confirm: 'Desea eliminar este ticket?' } %>


    	</td>
    	</tr>

    </tbody>
  <% end %>
<% else %>
  
<% end %>



</table>

<!-- Atras -->
<%= link_to(image_tag("atras-32.png"), tickets_path) %>
<%= link_to 'Atras', tickets_path %>

<%= will_paginate @troubles %>

app/views/troubles/edit.html.erb
<h1>Editing trouble</h1>

<%= render 'form' %>

<%= link_to 'Show', @trouble %> |
<%= link_to 'Back', troubles_path %>

app/views/troubles/index.html.erb
<h1>Tickets</h1> 


<!-- Grupo de botones redondos -->
<ul class="button-group round">
  <li><a href="#"><%= link_to 'Abiertos', abierto_path("abierto"), class: 'button tiny' %></a></li>
  <li><a href="#"><%= link_to 'Cerrados', cerrado_path("cerrado"), class: 'button tiny' %></a></li>
  <li><a href="#"><%= link_to 'Nuevo Ticket', new_trouble_path, class: 'button tiny' %></a></li>
</ul>

<!-- Fin grupo de botones redondos -->



<table>
  <tr>
    
    <th>Problema o solicitud</th>
    <th>Sucursal</th>
    <th>Usuario</th>
    <th>Importancia</th>
    <th>Estatus</th>
    <th>Categoria</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @troubles.each do |trouble| %>
  <tr>
  <div class="row">
    <div class="columns large-9 medium-6">
    <td><%= link_to trouble.title, trouble %></td>
    <td><%= trouble.client.name %></td>
    <td><%= trouble.user.name %> - <em><%= time_ago_in_words(trouble.created_at) %> ago</em></td>
    <td><%= trouble.severity %></td>
    <td><%= trouble.state %></td>
    <td><%= trouble.category %></td>
    <td><%= link_to 'Editar', edit_trouble_path(trouble) %></td>
    <td><%= link_to 'Eliminar', trouble, method: :delete, data: { confirm: 'Desea eliminar este ticket?' } %></td>
  </tr>
<% end %>
</table>

<br />



<%= will_paginate @troubles %>

app/views/troubles/new.html.erb
<%= render 'form' %>

<h6><%= link_to 'Atras', troubles_path %><h6>

app/views/troubles/show.html.erb
<!-- Editar -->
<%= link_to 'Editar', edit_trouble_path(@trouble) %>
<%= image_tag "editar-32.png" %>
<hr>

<% if @trouble.image? %>
<%= image_tag @trouble.image.url(:thumb) %>
<br />
<%= link_to @trouble.image.url, @trouble.image.url %>
<% end %>

<p>
  <strong>Titulo del problema o requerimiento:</strong>
  <h5><strong><%= @trouble.title %></strong></h5>
</p>
 
<p>
  <strong>Descripcion del problema o requerimiento:</strong>
  <h5><strong><%= @trouble.text %></strong></h5>
</p>

<p>
<%= @trouble.created_at.strftime("%b %d %Y a las %I:%M %p") %>
</p>

<p>
  <b>Usuario:</b>
  <%= @trouble.user.name %>
</p>

<p>
  <b>Importancia:</b>
  <%= @trouble.severity %>
</p>

<p>
  <b>Estatus:</b>
  <%= @trouble.state %>
</p>

<p>
  <b>Categoria:</b>
  <%= @trouble.category %>
</p>


<!-- Atras -->
<%= link_to(image_tag("atras-32.png"), troubles_path) %>
<%= link_to 'Atras', troubles_path %>



<hr>


 <!-- Despliega el modals de informacion importante -->
<a href="#" data-reveal-id="firstModal" class="radius button">Soluciones Aportadas</a>


<!-- Inicio del Modal -->
<div id="firstModal" class="reveal-modal" data-reveal>



  
<h3>Soluciones aportadas</h3>
<%= render @trouble.coments %>



  <p><a href="#" data-reveal-id="secondModal" class="secondary button">Aportar solucion...</a></p>
  <a class="close-reveal-modal">&#215;</a>
</div>

<div id="secondModal" class="reveal-modal" data-reveal>



  
  <h2>Agregar solucion:</h2>

<%= render 'coments/form' %>


  <a class="close-reveal-modal">&#215;</a>
</div>

 
<!-- Fin del Modal -->

app/views/troubles/show2.html.erb
<!-- Despliega el modals de informacion importante -->
<a href="#" data-reveal-id="firstModal" class="radius button"><%= @trouble.title %></a>


<!-- Inicio del Modal -->
<div id="firstModal" class="reveal-modal" data-reveal>



  <% if @trouble.image? %>
<%= image_tag @trouble.image.url(:thumb) %>
<br />
<%= link_to @trouble.image.url, @trouble.image.url %>


<% end %>

<p>
  <strong>Titulo del problema o requerimiento:</strong>
  <h5><strong><%= @trouble.title %></strong></h5>
</p>
 
<p>
  <strong>Descripcion del problema o requerimiento:</strong>
  <h5><strong><%= @trouble.text %></strong></h5>
</p>

<p>
<%= @trouble.created_at.strftime("%b %d %Y a las %I:%M %p") %>
</p>

<p>
  <b>Usuario:</b>
  <%= @trouble.user.name %>
</p>

<p>
  <b>Importancia:</b>
  <%= @trouble.severity %>
</p>

<p>
  <b>Estatus:</b>
  <%= @trouble.state %>
</p>

<p>
  <b>Categoria:</b>
  <%= @trouble.category %>
</p>

<hr>



  <p><a href="#" data-reveal-id="secondModal" class="secondary button">Aportar solucion...</a></p>
  <a class="close-reveal-modal">&#215;</a>
</div>

<div id="secondModal" class="reveal-modal" data-reveal>



  <h2>Agregar solucion:</h2>
<%= render 'coments/form' %>
 
<%= link_to 'Editar', edit_trouble_path(@trouble) %>
<%= link_to 'Atras', troubles_path %>


  <a class="close-reveal-modal">&#215;</a>
</div>

  <a class="close-reveal-modal">&#215;</a>
</div>
  <a class="close-reveal-modal">&#215;</a>
</div>

  <a class="close-reveal-modal">&#215;</a>
</div>
<!-- Fin del Modal -->