config/routes.rb
Micropost::Application.routes.draw do
 

 
  resources :troubles
  resources :troubles do
  resources :coments
end

  resources :works

  resources :clients

  resources :tickets

  get "welcome/index"

  resources :abouts

  resources :faqs

  resources :contacts

  resources :movies
 

  

  resources :employees

  resources :articles

  resources :articles do
  resources :comments
end

  devise_for :users

  resources :posts

  resources :users

  root :to => 'welcome#index'
  match 'troubles/:state/cerrado', to: 'troubles#cerrado', as: "cerrado"
  match 'troubles/:state/abierto',to: 'troubles#abierto',as:"abierto"
  

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  attr_accessible :apellidos, :cargo, :encargado, :celular, :ci, :correo, :departamento, :ext, :foto, :nombres, :sucursal, :telefono, :user
  attr_accessible :image
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/assets/default.jpg"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/


#before_save do
  #self.encargado.gsub!(/[\[\]\"]/, "") if attribute_present?("encargado")
#end




def self.search(search)

 if search 

    where(["nombres ILIKE ? OR encargado ILIKE ? OR apellidos ILIKE ? OR sucursal ILIKE ? OR departamento ILIKE ? OR encargado ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%"])

  

  else

    scoped

  end

end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  #Filter User before enter
  before_filter :authenticate_user!
  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
    @employees = Employee.search(params[:searchbox])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @employees }
    end
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @employee = Employee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/new
  # GET /employees/new.json
  def new
    @employee = Employee.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/1/edit
  def edit
    @employee = Employee.find(params[:id])
  
  end


  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'El empleado ha sido creado correctamente.' }
        format.json { render json: @employee, status: :created, location: @employee }
      else
        format.html { render action: "new" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    @employee = Employee.find(params[:id])

    respond_to do |format|
      if @employee.update_attributes(employee_params)
        format.html { redirect_to @employee, notice: 'El empleado ha sido actualizado correctamente.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url }
      format.json { head :no_content }
    end
  end

  private

    # Use this method to whitelist the permissible parameters. Example:
    # params.require(:person).permit(:name, :age)
    # Also, you can specialize this method with per-user checking of permissible attributes.
    def employee_params
      params.require(:employee).permit(:apellidos, :cargo, :celular, :ci, :correo, :departamento, :ext, :foto, :nombres, :sucursal, :telefono, :user, :image, :encargado => [])
end
end
  
      

      

app/helpers/employees_helper.rb
module EmployeesHelper

def checked(area)
  @employee.encargado.nil? ? false : @employee.encargado.match(area)
end


end

app/views/employees/_form.html.erb
<%= form_for(@employee, :html => { :multiple => true }) do |f| %>












  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
<%
=begin %>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.number_field :user %>
  </div>
<%
=end %>




<form>
  <fieldset>
    <legend><h2>Crear Empleado</h2></legend>

   
      <div class="field">
    <%= f.label :Foto %><br />
    <%= f.file_field :image %>
  </div>


  <div class="row">
    <div class="large-12 columns">
    <label><span data-tooltip aria-haspopup="true" class="has-tip" title="Favor escribir el nombre completo">Nombre Completo</span>
    <%= f.text_field :nombres %>
      </label>
    </div>
  </div>


  <div class="row">
    <div class="large-12 columns">
     <label><span data-tooltip aria-haspopup="true" class="has-tip" title="Favor escribir el apellido completo">Apellidos</span>
    <%= f.text_field :apellidos %>
    </label>
  </div>
  </div>


<%
=begin %>
Cedula o DNI
  <div class="row">
    <div class="large-6 columns">
    <label>DNI
    <%= f.text_field :ci %>
    </label>
  </div>
<%
=end %>
  
    <div class="row">
    <div class="large-12 columns">
    <label>Cargo
    <%= f.text_field :cargo %>
    </label>
  </div>
  </div>
 
  <div class="row">
    <div class="large-5 columns">
    <label>Numero Local
    <%= f.text_field :telefono %>
    </label>
  </div>
  
  <div class="large-2 columns">
    <label>Directo
    <%= f.text_field :ext %>
    </label>
  </div>

  <div class="large-5 columns">
    <label>Numero Celular
    <%= f.text_field :celular %>
    </label>
  </div>
  </div>

  <div class="row">
    <div class="large-12 columns">
    <label>Correo
    <%= f.text_field :correo %>
    </label>
  </div>
  </div>






<div class="row">
    <div class="large-6 columns">
     <label><span data-tooltip aria-haspopup="true" class="has-tip" title="Favor colocar la sucursal">Sucursal de</span>
    <%= f.select :sucursal, options_for_select([["-Seleccione-", "-Seleccione-"], ["GPSA", "GPSA"], ["BER", "BER"], ["BSC", "BSC"], ["BSJ", "BSJ"], ["BSF", "BSF"]]) %>
    </label>
  </div>
 



    <div class="large-6 columns">
     <label><span data-tooltip aria-haspopup="true" class="has-tip" title="Favor colocar el area responsable">Area</span>
    <%= f.select :departamento, options_for_select([["-Seleccione-", "-Seleccione-"], ["Bases de Datos", "Bases de Datos"], ["Sistemas", "Sistemas"], ["IT", "IT"], ["Operador", "Operador"], ["Programador", "Programador"]]) %>
    </label>
  </div>
  </div>




<ul>
</ul>

  <div class="row">
    <div class="large-20 columns">

 <label>Responsable de:


<%= label_tag 'encargado_Prisma', 'Prisma' %>
<%= check_box_tag 'employee[encargado][]', 'Prisma', checked('Prisma'), id: 'encargado_Prisma' %>

<%= label_tag 'encargado_Link', 'Link' %>
<%= check_box_tag 'employee[encargado][]', 'Link', checked('Link'), id: 'encargado_Link' %>

<%= label_tag 'encargado_GOA', 'GOA' %>
<%= check_box_tag 'employee[encargado][]', 'GOA', checked('GOA'), id: 'encargado_GOA' %>

<%= label_tag 'encargado_Tracking', 'Tracking' %>
<%= check_box_tag 'employee[encargado][]', 'Tracking', checked('Tracking'), id: 'encargado_Tracking' %>

<%= label_tag 'encargado_Credencial', 'Credencial' %>
<%= check_box_tag 'employee[encargado][]', 'Credencial', checked('Credencial'), id: 'encargado_Credencial' %>

<%= label_tag 'encargado_QUALIA', 'QUALIA' %>
<%= check_box_tag 'employee[encargado][]', 'QUALIA', checked('QUALIA'), id: 'encargado_QUALIA' %>

<%= label_tag 'encargado_SFB', 'SFB' %>
<%= check_box_tag 'employee[encargado][]', 'SFB', checked('SFB'), id: 'encargado_SFB' %>

<%= label_tag 'encargado_Engage', 'Engage' %>
<%= check_box_tag 'employee[encargado][]', 'Engage', checked('Engage'), id: 'encargado_Engage' %>

<%= label_tag 'encargado_Bid', 'Bid' %>
<%= check_box_tag 'employee[encargado][]', 'Bid', checked('Bid'), id: 'encargado_Bid' %>

<%= label_tag 'encargado_Sancor', 'Sancor' %>
<%= check_box_tag 'employee[encargado][]', 'Sancor', checked('Sancor'), id: 'encargado_Sancor' %>

  </label>
  </div>
  </div>

<ul>
</ul>


   <div class="actions">

    <%= f.submit 'Guardar', class: 'button tiny' %>
    <%= link_to 'Atras', employees_path, class: 'button tiny' %>
   
    
  </div>







  </fieldset>
</form>

<% end %>


<!-- Pie de pagina con los links de retorno --> 
<div class="icon-bar five-up" role="navigation">
  
    
    <label id='itemlabel1'><%= link_to 'Home', root_path %></label>
  </a>

    
    <label id='itemlabel2'><%= link_to 'Preguntas', faqs_path %></label>
  </a>
  
    
    <label id='itemlabel3'><%= link_to 'Nosotros', abouts_path %></label>
  </a>
  
    
    <label id='itemlabel4'><%= link_to 'Contactanos', contacts_path %></label>
  </a>
  
</div>




<!-- Pie de pagina con nombre de creador --> 

<dl class="sub-nav">
  <dt>Creado por:</dt>
  <dd class="active"><a href="#">Rogger Herrera</a></dd>
  <dd><a href="#">Banco San Juan S.A</a></dd>
  <dd><a href="#">2019</a></dd>
</dl>

app/views/employees/edit.html.erb
<h1>Editar Empleado</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @employee %> |
<%= link_to 'Atras', employees_path %>

app/views/employees/index.html.erb
<ul class="inline-list">
<right><h4><%= link_to 'Nuevo Empleado', new_employee_path %></h4></right>
</ul>

<%= image_tag "empleado.png" %>

<ul>

</ul>

<%= form_tag({:controller => "employees", :action => "index"}, :method => :get) do %>

    <%= text_field_tag "searchbox", params[:searchbox] %>

    <%= submit_tag "Buscar", class: 'button tiny' %>

<% end %>






<% @employees.each do |employee| %>
<hr>
  <h3><%= link_to employee.nombres, employee %><td> <%= link_to employee.apellidos, employee %></td></h3>

<div class="row">
 <div class="columns large-9 medium-6">

 

    <td><%= image_tag employee.image.url(:thumb) %></td>
    <td><%= employee.encargado %></td><td>  
    <td><%= link_to employee.sucursal, employee %></td> 
   </div>


    
    <div class="columns large-3 medium-6">
    
    <ul class="inline-list">
    
    <li><%= link_to 'Editar', edit_employee_path(employee) %></li>
    <li><%= link_to 'Eliminar', employee, method: :delete, data: { confirm: 'Desea eliminar este empleado?' } %></li>
  </ul>

</div>
</div>


<% end %>


<br/>

app/views/employees/index2.html.erb
<ul class="inline-list">
<li><h4><%= link_to 'Nuevo Empleado', new_employee_path %></h4></li>
</ul>

<%= image_tag "emplead.jpg" %>





<%= form_tag({:controller => "employees", :action => "index"}, :method => :get) do %>

    <%= text_field_tag "searchbox", params[:searchbox] %>

    <%= submit_tag "Buscar", class: 'button' %>

<% end %>





<% @employees.each do |employee| %>
<hr>
  <h2><%= link_to employee.nombres, employee %></h2>

<div class="row">
 <div class="columns large-9 medium-6">


 

    <td><%= image_tag employee.image.url(:thumb) %></td>
    <td><%= employee.apellidos %></td> => <td><%= employee.cargo %></td>
   </div>
    
    <div class="columns large-3 medium-6">
    
    <ul class="inline-list">
    
    <li><%= link_to 'Editar', edit_employee_path(employee) %></li>
    <li><%= link_to 'Eliminar', employee, method: :delete, data: { confirm: 'Desea eliminar este empleado?' } %></li>
  </ul>

</div>
</div>


<% end %>


<br />

<%= link_to 'Nuevo empleado', new_employee_path %>

app/views/employees/new.html.erb
<%= render 'form' %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @employee.user %>
</p>





<% if @employee.image? %>
<%= image_tag @employee.image.url(:thumb) %>
<br />
<%= link_to @employee.image.url, @employee.image.url %>
<% end %>

<p>
  <b>Foto:</b>
  <%= @employee.foto %>
</p>

<p>
  <b>Nombres:</b>
  <%= @employee.nombres %>
</p>

<p>
  <b>Apellidos:</b>
  <%= @employee.apellidos %>
</p>

<p>
  <b>Ci:</b>
  <%= @employee.ci %>
</p>

<p>
  <b>Cargo:</b>
  <%= @employee.cargo %>
</p>

<p>
  <b>Telefono:</b>
  <%= @employee.telefono %>
</p>

<p>
  <b>Ext:</b>
  <%= @employee.ext %>
</p>

<p>
  <b>Celular:</b>
  <%= @employee.celular %>
</p>

<p>
  <b>Correo:</b>
  <%= @employee.correo %>
</p>

<p>
  <b>Sucursal:</b>
  <%= @employee.sucursal %>
</p>

<p>
  <b>Departamento:</b>
  <%= @employee.departamento %>
</p>

<p>
  <b>Encargado de:</b>
  <%= @employee.encargado.inspect %>
</p>





<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>