config/routes.rb
Micropost::Application.routes.draw do
 

 
  resources :troubles
  resources :troubles do
  resources :coments
end

  resources :works

  resources :clients

  resources :tickets

  get "welcome/index"

  resources :abouts

  resources :faqs

  resources :contacts

  resources :movies
 

  

  resources :employees

  resources :articles

  resources :articles do
  resources :comments
end

  devise_for :users

  resources :posts

  resources :users

  root :to => 'welcome#index'
  match 'troubles/:state/cerrado', to: 'troubles#cerrado', as: "cerrado"
  match 'troubles/:state/abierto',to: 'troubles#abierto',as:"abierto"
  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities

if user.has_role? :admin
  can :manage, :all
else
  can :read, :all
end


    
  end
end

app/models/about.rb
class About < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/article.rb
class Article < ActiveRecord::Base

  resourcify
  belongs_to :user
  attr_accessible :text, :title
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
def self.search(search)

 if search 
 
    where(["title ILIKE ? OR text ILIKE ?", "%#{search}%", "%#{search}%"])

  else

    scoped

  end

end


end

app/models/client.rb
class Client < ActiveRecord::Base
belongs_to :user
  attr_accessible :address, :email, :name, :phone, :user_id

  has_many :tickets
  has_many :troubles
end

app/models/comen.rb
class Comen < ActiveRecord::Base
  belongs_to :movie
  attr_accessible :body, :commenter
end

app/models/coment.rb
class Coment < ActiveRecord::Base
  belongs_to :trouble
  attr_accessible :body, :commenter
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :user
  attr_accessible :body, :commenter, :user_id
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	belongs_to :user
  # attr_accessible :title, :body
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  attr_accessible :apellidos, :cargo, :encargado, :celular, :ci, :correo, :departamento, :ext, :foto, :nombres, :sucursal, :telefono, :user
  attr_accessible :image
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/assets/default.jpg"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/


#before_save do
  #self.encargado.gsub!(/[\[\]\"]/, "") if attribute_present?("encargado")
#end




def self.search(search)

 if search 

    where(["nombres ILIKE ? OR encargado ILIKE ? OR apellidos ILIKE ? OR sucursal ILIKE ? OR departamento ILIKE ? OR encargado ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%"])

  

  else

    scoped

  end

end
end

app/models/faq.rb
class Faq < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/movie.rb
class Movie < ActiveRecord::Base
 

  attr_accessible :cast, :director, :duration, :genre, :production, :rating, :sinop, :title, :user_id, :year, :image

  belongs_to :user

has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/assets/movies.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/


end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :user_id

belongs_to :user
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
  # attr_accessible :title, :body
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
belongs_to :user
  attr_accessible :client_id, :problem, :status, :user_id, :image
belongs_to :client
  
  

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/assets/movies.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/trouble.rb
class Trouble < ActiveRecord::Base
	has_many :coments, dependent: :destroy

	belongs_to :client
	belongs_to :user
  attr_accessible :category, :client_id, :severity, :state, :text, :title, :user_id, :image

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/assets/movies.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/


end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :description, :email, :location, :name

has_many :posts
has_many :articles
has_many :comments
has_many :movies
has_many :contacts
has_many :tickets
has_many :clients
has_many :troubles
end

app/models/work.rb
class Work < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
   before_filter :authenticate_user!
   http_basic_authenticate_with name: "cano19781", password: "caracas1", except: [:index, :show]
  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
    @search = Movie.search(params[:search])   
    @movies = @search.all  
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @movies }
    end
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @movie = Movie.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @movie }
    end
  end

  # GET /movies/new
  # GET /movies/new.json
  def new
    @movie = Movie.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @movie }
    end
  end

  # GET /movies/1/edit
  def edit
    @movie = Movie.find(params[:id])
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'La pelicula ha sido creada correctamente.' }
        format.json { render json: @movie, status: :created, location: @movie }
      else
        format.html { render action: "new" }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    @movie = Movie.find(params[:id])

    respond_to do |format|
      if @movie.update_attributes(movie_params)
        format.html { redirect_to @movie, notice: 'La pelicula ha sido actualizada correctamente.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url }
      format.json { head :no_content }
    end
  end

  private

    # Use this method to whitelist the permissible parameters. Example:
    # params.require(:person).permit(:name, :age)
    # Also, you can specialize this method with per-user checking of permissible attributes.
    def movie_params
      params.require(:movie).permit(:cast, :director, :duration, :genre, :production, :rating, :sinop, :title, :user_id, :year, :image)
    end
end

app/helpers/comen_helper.rb
module ComenHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/movies/_form.html.erb
<%= form_for(@movie, :html => { :multipart => true }) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<!-- Poster de la pelicula --> 

<div class="row">
    <div class="large-12 columns">
    <label><span data-tooltip aria-haspopup="true" class="has-tip" title="Colocar poster de la pelicula">Poster de la pelicula</span>
    <%= f.file_field :image %>
      </label>
    </div>


    <form>
  <fieldset>
    <legend><h2>Crear Ticket</h2></legend>
  

<!-- Titulo de la pelicula --> 


    <div class="large-12 columns">
    <label><span data-tooltip aria-haspopup="true" class="has-tip" title="Colocar el titulo de la pelicula">Titulo de la pelicula</span>
    <%= f.text_field :title %>
      </label>
    </div>



<!-- Sinopsis de la pelicula --> 

    <div class="row">
    <div class="large-12 columns">
  <label><span data-tooltip aria-haspopup="true" class="has-tip" title="Colocar la sinopsis de la pelicula">Sinopsis de la pelicula</span> 
    <%= f.text_area :sinop, :cols => "30", :rows => "10" %>
    </label>
 </div>


<!-- Genero de la pelicula --> 

 
<div class="large-6 columns">
    <label><span data-tooltip aria-haspopup="true" class="has-tip" title="Colocar el genero de la pelicula">Genero</span>
  <% genero = {'-Seleccione-' => '-Seleccione-', 'Comedia' => 'Comedia', 'Accion' => 'Accion', 'Terror' => 'Terror',} %>
    <%= f.select :genre,genero %>
     </label>
    </div>


<!-- Rating de la pelicula --> 


    <div class="large-6 columns">
    <label><span data-tooltip aria-haspopup="true" class="has-tip" title="Colocar el rating de la pelicula">Rating de la pelicula</span>
    <%= f.number_field :rating %>
      </label>
    </div>


<!-- Productora de la pelicula --> 


    <div class="large-6 columns">
    <label><span data-tooltip aria-haspopup="true" class="has-tip" title="Colocar la productora de la pelicula">Productora de la pelicula</span>
    <%= f.text_field :production %>
      </label>
    </div>
  

<!-- Año de la pelicula --> 


    <div class="large-6 columns">
    <label><span data-tooltip aria-haspopup="true" class="has-tip" title="Colocar el año de la pelicula">Año de la pelicula</span>
    <%= f.number_field :year %>
      </label>
    </div>


<!-- Duracion de la pelicula --> 


    <div class="large-6 columns">
    <label><span data-tooltip aria-haspopup="true" class="has-tip" title="Colocar la duracion de la pelicula">Duracion de la pelicula</span>
    <%= f.text_field :duration %>
      </label>
    </div>
  
  
<!-- Director de la pelicula --> 


    <div class="large-6 columns">
    <label><span data-tooltip aria-haspopup="true" class="has-tip" title="Colocar el director de la pelicula">Director de la pelicula</span>
    <%= f.text_field :director %>
      </label>
    </div>  
  

<!-- Reparto de la pelicula --> 


    <div class="large-12 columns">
    <label><span data-tooltip aria-haspopup="true" class="has-tip" title="Colocar el reparto de la pelicula">Reparto de la pelicula</span>
    <%= f.text_field :cast %>
      </label>
    </div>


<!-- Campo para definir usuario -->

<%
=begin %>
<div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
<%
=end %>


 <div class="actions">
  <%= f.submit 'Guardar', class: 'button tiny' %>
    <%= link_to 'Atras', movies_path, class: 'button tiny' %>
    </div>


 </fieldset>
</form>
<% end %>

 </fieldset>
</form>



<!-- Pie de pagina con los links de retorno --> 
<div class="icon-bar five-up" role="navigation">
  
    
    <label id='itemlabel1'><%= link_to 'Home', root_path %></label>
  </a>

    
    <label id='itemlabel2'><%= link_to 'Preguntas', faqs_path %></label>
  </a>
  
    
    <label id='itemlabel3'><%= link_to 'Nosotros', abouts_path %></label>
  </a>
  
    
    <label id='itemlabel4'><%= link_to 'Contactanos', contacts_path %></label>
  </a>
  
</div>



<!-- Pie de pagina con nombre de creador --> 

<dl class="sub-nav">
  <dt>Creado por:</dt>
  <dd class="active"><a href="#">Rogger Herrera</a></dd>
  <dd><a href="#">Propacine S.R.L</a></dd>
  <dd><a href="#">2014</a></dd>
</dl>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<!-- 
Crear peliculas -->

<ul class="inline-list">
<li><h4><%= link_to 'Crear Pelicula', new_movie_path %></h4></li> 
</ul>


<!-- 
Imagen principal que se mueve -->

<ul class="example-orbit-content" data-orbit>
  <li data-orbit-slide="headline-1">
    <div>
     
      <h3><%= image_tag "movie.jpg" %></h3>
    </div>
  </li>
  <li data-orbit-slide="headline-2">
    <div>
      
      <h3><%= image_tag "movie.jpg" %></h3>
    </div>
  </li>
  <li data-orbit-slide="headline-3">
    <div>
      
      <h3><%= image_tag "movie.jpg" %></h3>
    </div>
  </li>
</ul>

<!-- 
<h1>Sinopsis</h1> -->

<!-- 

<div class="flex-video widescreen vimeo">
  <iframe src="http://player.vimeo.com/video/114885009" width="400" height="225" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
</div> 

-->

<!-- Busqueda -->

<div class="large-3 columns">
<%= form_for @search do |f| %>
  
<%= f.submit 'Buscar', class: 'button' %><%= f.text_field :title_contains %>   
<% end %> 


    




<hr>
<table>
  <tr>
    <th>Imagen</th>
    <th>Pelicula</th>
    <th>Genero</th>
  
    
    
    <th>Año</th>
    <th>Duracion</th>
    <th>Director</th>
   
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @movies.each do |movie| %>
  <tr>
  <td><%= image_tag movie.image.url(:thumb) %></td>
    <td><%= movie.title %></td>
    
    <td><%= movie.genre %></td>
    
    
    
    <td><%= movie.year %></td>
    <td><%= movie.duration %></td>
    <td><%= movie.director %></td>
    
    <td><%= link_to 'Show', movie %></td>
    <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
    <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<h1>Crear Pelicula</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<% if @movie.image? %>
<%= image_tag @movie.image.url(:thumb) %>
<br />
<%= link_to @movie.image.url, @movie.image.url %>
<% end %>

<p>
  <b>Title:</b>
  <%= @movie.title %>
</p>

<p>
  <b>Sinop:</b>
  <%= @movie.sinop %>
</p>

<p>
  <b>Genre:</b>
  <%= @movie.genre %>
</p>

<p>
  <b>Rating:</b>
  <%= @movie.rating %>
</p>

<p>
  <b>Production:</b>
  <%= @movie.production %>
</p>

<p>
  <b>User:</b>
  <%= @movie.user_id %>
</p>

<p>
  <b>Year:</b>
  <%= @movie.year %>
</p>

<p>
  <b>Duration:</b>
  <%= @movie.duration %>
</p>

<p>
  <b>Director:</b>
  <%= @movie.director %>
</p>

<p>
  <b>Cast:</b>
  <%= @movie.cast %>
</p>


<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>